-- ELIMINAR LAS TABLAS
DROP PROCEDURE SIMULACION;
DROP PACKAGE MODULO_INICIO;
DROP PACKAGE MODULO_SERVICIO;
DROP PACKAGE MODULO_PAQUETE;
DROP PACKAGE MODULO_COMPRA;
DROP PACKAGE MODULO_MANTENIMIENTO;
DROP PACKAGE MODULO_OBSERVACION;

DROP TABLE VENTA;
DROP TABLE COMPETENCIA;
DROP TABLE MPAGO;
DROP TABLE DETFACTURA;
DROP TABLE FACTURA;
DROP TABLE MEDIO;
DROP TABLE PCR;
DROP TABLE PROPIETARIO;
DROP TABLE SUBSCRIPCION;
DROP TABLE PAQUETE;
DROP TABLE OBSERVACION;
DROP TABLE CLIENTE;
DROP TABLE MANTENIMIENTO;
DROP TABLE DISPONIBILIDAD;
DROP TABLE SERVICIO;
DROP TABLE ALIANZA;
DROP TABLE DESTINO;
DROP TABLE CRUCERO;
DROP TABLE PAIS;
DROP TABLE PROVEEDOR; 
DROP TABLE METODOS_PAGO;

-- ELIMINAR LAS SECUENCIAS

DROP SEQUENCE id_proveedor;
DROP SEQUENCE id_pais;
DROP SEQUENCE id_crucero;
DROP SEQUENCE id_destino;
DROP SEQUENCE id_alianza_s;
DROP SEQUENCE id_servicio_s;
DROP SEQUENCE id_disponibilidad_s;
DROP SEQUENCE id_mantenimiento_s;
DROP SEQUENCE id_cliente;
DROP SEQUENCE id_observacion_s;
DROP SEQUENCE id_paquete;
DROP SEQUENCE id_pcr;
DROP SEQUENCE id_medio;
DROP SEQUENCE id_factura_s;
DROP SEQUENCE id_detfactura_s;
DROP SEQUENCE id_mpago_s;
DROP SEQUENCE id_competencia;

-- PROCEDURES
drop PROCEDURE REPORTE_1;
drop PROCEDURE REPORTE_2;
drop PROCEDURE REPORTE_3;
drop PROCEDURE REPORTE_4;
drop PROCEDURE REPORTE_5;
drop PROCEDURE REPORTE_6;
drop PROCEDURE REPORTE_7;
drop PROCEDURE REPORTE_7_G;
drop PROCEDURE REPORTE_8;
drop PROCEDURE REPORTE_8_G;
drop PROCEDURE REPORTE_9;
drop PROCEDURE REPORTE_10;
drop PROCEDURE REPORTE_11;
drop PROCEDURE REPORTE_12;
drop PROCEDURE REPORTE_12_G;
drop PROCEDURE REPORTE_13;
DROP PROCEDURE INSERTAR_PAIS;
DROP PROCEDURE INSERTAR_CRUCERO;
DROP PROCEDURE INSERTAR_DESTINO;
DROP PROCEDURE INSERTAR_PROVEEDOR;
DROP PROCEDURE INSERTAR_COMPETENCIA;
DROP FUNCTION aceptar_o_rechazar;
DROP FUNCTION RANDOM_DATE;


-- ELIMINAR LOS TDA
DROP TYPE FECHA_RANGO;
DROP TYPE DATOS_USUARIO;
DROP TYPE BALANCE;

alter session set "_oracle_script"=true;
Revoke empleado from EMPLEADO1;
DROP USER EMPLEADO1 CASCADE ;
DROP ROLE EMPLEADO;

Revoke administrador from ADMINISTRADOR1;
DROP USER ADMINISTRADOR1 CASCADE ;
DROP ROLE administrador;

Revoke gerente_ventas from GERENTE1;
DROP USER GERENTE1 CASCADE ;
DROP ROLE gerente_ventas;
