-- ELIMINAR LAS TABLAS
DROP PACKAGE MODULO_INICIO;
DROP PACKAGE MODULO_SERVICIO;
DROP PACKAGE MODULO_PAQUETE;
DROP PACKAGE MODULO_COMPRA;

DROP TABLE VENTA;
DROP TABLE COMPETENCIA;
DROP TABLE MPAGO;
DROP TABLE DETFACTURA;
DROP TABLE FACTURA;
DROP TABLE MEDIO;
DROP TABLE PCR;
DROP TABLE PROPIETARIO;
DROP TABLE SUBSCRIPCION;
DROP TABLE PAQUETE;
DROP TABLE OBSERVACION;
DROP TABLE CLIENTE;
DROP TABLE MANTENIMIENTO;
DROP TABLE DISPONIBILIDAD;
DROP TABLE SERVICIO;
DROP TABLE ALIANZA;
DROP TABLE DESTINO;
DROP TABLE CRUCERO;
DROP TABLE PAIS;
DROP TABLE PROVEEDOR; 
DROP TABLE METODOS_PAGO;

-- ELIMINAR LAS SECUENCIAS

DROP SEQUENCE id_proveedor;
DROP SEQUENCE id_pais;
DROP SEQUENCE id_crucero;
DROP SEQUENCE id_destino;
DROP SEQUENCE id_alianza_s;
DROP SEQUENCE id_servicio_s;
DROP SEQUENCE id_disponibilidad_s;
DROP SEQUENCE id_mantenimiento;
DROP SEQUENCE id_cliente;
DROP SEQUENCE id_observacion;
DROP SEQUENCE id_paquete;
DROP SEQUENCE id_pcr;
DROP SEQUENCE id_medio;
DROP SEQUENCE id_factura_s;
DROP SEQUENCE id_detfactura_s;
DROP SEQUENCE id_mpago_s;
DROP SEQUENCE id_competencia;

-- PROCEDURES
drop PROCEDURE REPORTE_1;
drop PROCEDURE REPORTE_2;
drop PROCEDURE REPORTE_3;
drop PROCEDURE REPORTE_4;
DROP PROCEDURE INSERTAR_PAIS;
DROP PROCEDURE INSERTAR_CRUCERO;
DROP PROCEDURE INSERTAR_DESTINO;
DROP PROCEDURE INSERTAR_PROVEEDOR;
DROP FUNCTION aceptar_o_rechazar;
DROP FUNCTION RANDOM_DATE;


-- ELIMINAR LOS TDA
DROP TYPE FECHA_RANGO;
DROP TYPE DATOS_USUARIO;
DROP TYPE BALANCE;

