CREATE OR REPLACE PROCEDURE INSERTAR_BLOB(V_blob BLOB, V_nombre VARCHAR(100))
IS 
BEGIN
    DECLARE
    V_bfile BFILE;
BEGIN
    V_bfile := BFILENAME('ORACLECLRDIR', V_nombre);
    DBMS_LOB.OPEN(V_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(V_blob, V_bfile, SYS.DBMS_LOB.GETLENGTH(V_bfile));
    DBMS_LOB.CLOSE(V_bfile);
    COMMIT;
    END;
END;